spring:
  main:
    banner-mode: off
  datasource:
    # Mysql公共参数
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.163.128:3306/handsome?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: handsome
    # HikariCP 连接池配置
    hikari:
      pool-name: exercise_HikariCP
      minimum-idle: 5  #最小空闲连接数量
      idle-timeout: 30000  #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 200  #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000  #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000  #数据库连接超时时间,默认30秒，即30000

#mybatis
mybatis:
  type-aliases-package: com.example.skywalkingapp.entity
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    root: error